mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('polls/',include('polls.urls')),
    path('admin/', admin.site.urls)
]

mysite/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    # /polls/
    path('', views.IndexView.as_view(), name='index'),
    # /polls/5/
    path('<int:pk>/',views.DetailView.as_view(),name='detail'),
    # /polls/5/results/
    path('<int:pk>/results',views.ResultsView.as_view(), name='results'),
    # /polls/5/vote
    path('<int:question_id>/vote/', views.vote,name='vote'),
    # /polls/add
    path('add/',views.add_page,name='add'),
    # /polls/add_question
    path('add/add_question',views.add_question,name='add_question')
]

mysite/polls/models.py
import datetime

from django.utils import timezone
from django.db import models


# Create your models here.
class Question(models.Model):
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')


class Choice(models.Model):
    def __str__(self):
        return self.choice_text
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

mysite/polls/forms.py
from django import forms

class QuestionForm(forms.Form):
    question_text = forms.CharField(label='Question',max_length=100)

mysite/polls/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render,get_object_or_404
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Question, Choice

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'
    def get_queryset(self):
        """
        excludes questions that are not published yet
        """
        return Question.objects.filter(pub_date__lte=timezone.now())

def add_page(request):
    return render(request,'polls/add.html')

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

'''
def index(request):

    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {
        'latest_question_list': latest_question_list,
    }
    return render(request,'polls/index.html',context)

def detail(request,question_id):
    question = get_object_or_404(Question,pk=question_id)
    return render(request,'polls/detail.html',{'question': question})

def results(request,question_id):
    question = get_object_or_404(Question,pk=question_id)
    return render(request,'polls/results.html',{'question':question})

'''

def vote(request,question_id):
    question = get_object_or_404(Question,pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError,Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request,'polls/detail.html',{
            'question':question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results',args=(question_id,)))
        #return render(request,'polls/results',{'question_id':question_id})

def add_question(request):
    return HttpResponseRedirect(reverse('polls:index'))

mysite/polls/templates/polls/add.html
{% extends 'polls/base.html' %}
{% load static %}

{% block content %}
    <form name="question_form" action="{% url 'polls:add_question' %}" onsubmit="return ValidateForm()" method="post">
        {% csrf_token %}
        Question:<br>
        <input type="text" name="question"><br>
        Add Choices to the question:<br>
        <input type="text" id="txt_choice"/>
        <input type="button" value="Add choice" id="add_choice" onclick="AddChoiceToList()">
        <ul id="choices_list"></ul>
        <input type="submit" value="Confirm">
    </form>
    <script src="{% static 'polls/js/add_choice_to_list.js' %}"></script>
    <script src="{% static 'polls/js/validate_form.js' %}"></script>

{% endblock %}

mysite/polls/templates/polls/base.html
{% load static %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
</head>

<body>
    <div class="page-header">
        <nav class="navbar navbar-light bg-dark">
        <span class="navbar-brand mb-0 h1">Polls Application</span>
        </nav>
    </div>

    <div class="page-content">
        {% block content %}
        {% endblock %}
    </div>

</body>

mysite/polls/templates/polls/detail.html
{% extends 'polls/base.html' %}

{% block content %}
    <h2>{{ question.question_text }}</h2>

    {% if error_message %}<p id="error_message"><strong>{{ error_message }}</strong></p>{% endif %}


    <form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <div class="radio">
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        </div>
    {% endfor %}
    <input type="submit" value="Vote">
    </form >
{% endblock %}

mysite/polls/templates/polls/index.html
{% extends 'polls/base.html' %}

{% block content %}

    {% if latest_question_list %}

    <ul class="list-group">
    {% for question in latest_question_list %}
        <li class="list-group-item"><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}
    <a href="{% url 'polls:add' %}"><button>Add a Question</button></a>

{% endblock %}

mysite/polls/templates/polls/results.html
{% extends 'polls/base.html' %}

{% block content %}
    <h2>{{ question.question_text }}</h2>

    <ul class="list-group">
    {% for choice in question.choice_set.all %}
        <li class="list-group-item">{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
    </ul>

    <a id="vote_again" href="{% url 'polls:detail' question.id %}">Vote again?</a>
{% endblock %}